// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLRE7tO7G2beOJH8PGxLSYwQCJPQFVuGI',
    appId: '1:962202748601:web:2ec07af599376e5696fd68',
    messagingSenderId: '962202748601',
    projectId: 'listynest',
    authDomain: 'listynest.firebaseapp.com',
    storageBucket: 'listynest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvICC68iz4UnUMJKSX2Ke4fLw-vSlkbY8',
    appId: '1:962202748601:android:d2f323a000f558f496fd68',
    messagingSenderId: '962202748601',
    projectId: 'listynest',
    storageBucket: 'listynest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAojrucFYwk-iI7Fg97jpK1LZ8ngXWvu5c',
    appId: '1:962202748601:ios:9400e1df0e61184696fd68',
    messagingSenderId: '962202748601',
    projectId: 'listynest',
    storageBucket: 'listynest.firebasestorage.app',
    iosBundleId: 'com.example.listynest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAojrucFYwk-iI7Fg97jpK1LZ8ngXWvu5c',
    appId: '1:962202748601:ios:9400e1df0e61184696fd68',
    messagingSenderId: '962202748601',
    projectId: 'listynest',
    storageBucket: 'listynest.firebasestorage.app',
    iosBundleId: 'com.example.listynest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLRE7tO7G2beOJH8PGxLSYwQCJPQFVuGI',
    appId: '1:962202748601:web:ccbd92bc0ca2931496fd68',
    messagingSenderId: '962202748601',
    projectId: 'listynest',
    authDomain: 'listynest.firebaseapp.com',
    storageBucket: 'listynest.firebasestorage.app',
  );
}
