
import 'package:flutter/material.dart';
import 'package:listynest/models/ad.dart';

class AddAdForm extends StatefulWidget {
  final Function(Ad) onAdAdded;

  const AddAdForm({super.key, required this.onAdAdded});

  @override
  AddAdFormState createState() => AddAdFormState();
}

class AddAdFormState extends State<AddAdForm> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  final _priceController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        children: [
          TextFormField(
            controller: _titleController,
            decoration: const InputDecoration(labelText: 'Title'),
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Please enter a title';
              }
              return null;
            },
          ),
          TextFormField(
            controller: _descriptionController,
            decoration: const InputDecoration(labelText: 'Description'),
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Please enter a description';
              }
              return null;
            },
          ),
          TextFormField(
            controller: _priceController,
            decoration: const InputDecoration(labelText: 'Price'),
            keyboardType: TextInputType.number,
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Please enter a price';
              }
              return null;
            },
          ),
          ElevatedButton(
            onPressed: () {
              if (_formKey.currentState!.validate()) {
                final ad = Ad(
                  id: '', // The ID will be generated by Firestore
                  title: _titleController.text,
                  description: _descriptionController.text,
                  price: double.parse(_priceController.text),
                  category: '', // You might want to add a category field
                  location: Location(country: '', state: '', city: '' ), // You might want to add a location field
                  imageUrls: [],
                  expiresAt: DateTime.now().add(const Duration(days: 30)),
                  createdAt: DateTime.now(),
                  updatedAt: DateTime.now(), userId: '', // The user ID will be set in the provider

                );
                widget.onAdAdded(ad);
              }
            },
            child: const Text('Add Ad'),
          ),
        ],
      ),
    );
  }
}
